# Generated by Django 4.1.2 on 2022-10-31 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('type', models.CharField(default='comment', max_length=200)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.URLField(blank=True)),
                ('comment', models.TextField(max_length=90)),
                ('contentType', models.CharField(default='text/markdown', max_length=200)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentSrc',
            fields=[
                ('type', models.CharField(default='comments', max_length=200)),
                ('page', models.PositiveIntegerField(default=1)),
                ('size', models.PositiveIntegerField(default=5)),
                ('post', models.URLField(blank=True)),
                ('id', models.URLField(blank=True, primary_key=True, serialize=False)),
                ('comments', models.ManyToManyField(blank=True, to='comment.comment')),
            ],
        ),
    ]
