# Generated by Django 4.1.2 on 2022-10-27 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='user_permissions',
        ),
    ]
