# Generated by Django 4.1.2 on 2022-11-01 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('follower', '0002_remove_follower_followers_follower_friends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='friends',
        ),
        migrations.AddField(
            model_name='follower',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
