# Generated by Django 4.1.2 on 2022-11-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower', '0003_remove_follower_friends_follower_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='type',
        ),
        migrations.RemoveField(
            model_name='followrequest',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='followrequest',
            name='type',
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
