# Generated by Django 4.1.2 on 2022-10-26 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrequest',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='followrequest',
            name='object',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
        migrations.DeleteModel(
            name='FollowRequest',
        ),
    ]
