# Generated by Django 4.1.2 on 2022-10-26 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
